config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('dogs.urls', namespace='dogs')),
                  path('users/', include('users.urls', namespace='users')),
                  path('reviews/', include('reviews.urls', namespace='reviews')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from dogs.views import index, \
    DogsListView, DogCreateView, DogDetailView, DogUpdateView, DogDeleteView, CategoryListView, DogDeactivateListView, \
    dog_toggle_activity, DogsSearchListView, DogsCategorySearchListView
from dogs.apps import DogsConfig

app_name = DogsConfig.name

urlpatterns = [
    path('', cache_page(60)(index), name='index'),
    path('categories/', cache_page(60)(CategoryListView.as_view()), name='categories'),
    path('categories/<int:pk>/dogs', cache_page(60)(CategoryListView.as_view()), name='category_dogs'),
    path('dogs/', never_cache(DogsListView.as_view()), name='list_dogs'),
    path('dogs/deactivate/', DogDeactivateListView.as_view(), name='deactivated_list_dogs'),
    path('dogs/search/', DogsSearchListView.as_view(), name='search_dogs'),
    path('dogs/search/category/', DogsCategorySearchListView.as_view(), name='search_category_dogs'),
    path('dogs/create/', DogCreateView.as_view(), name='create_dog'),
    path('dogs/detail/<int:pk>/', never_cache(DogDetailView.as_view()), name='detail_dog'),
    path('dogs/update/<int:pk>/', never_cache(DogUpdateView.as_view()), name='update_dog'),
    path('dogs/toggle/<int:pk>/', dog_toggle_activity, name='toggle_activity_dog'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='delete_dog'),
]

reviews/urls.py
from django.urls import path
from reviews.apps import ReviewsConfig
from reviews.views import ReviewListView, DogReviewListViewAll, DogReviewDetailView, DogReviewCreateView, \
    ReviewUpdateView, DogReviewDeleteView, review_toggle_activity

app_name = ReviewsConfig.name

urlpatterns = [
    path('', ReviewListView.as_view(), name='list_reviews'),
    path('deactivated/', DogReviewListViewAll.as_view(), name='deactivated_reviews'),
    path('review/detail/<slug:slug>/', DogReviewDetailView.as_view(), name='detail_review'),
    path('review/create/', DogReviewCreateView.as_view(), name='create_review'),
    path('review/update/<slug:slug>/', ReviewUpdateView.as_view(), name='update_review'),
    path('review/delete/<slug:slug>/', DogReviewDeleteView.as_view(), name='delete_review'),
    path('review/toogle/<slug:slug>/', review_toggle_activity, name='toggle_activity_review'),
]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import user_generate_new_password, UserRegisterView, \
    UserLoginView, UserProfileView, UserUpdateView, UserChangePasswordView, UserLogoutView, UserListView, UserProfileListView

app_name = UsersConfig.name

urlpatterns = [
    # работа с аккаунтом пользователя
    path('', UserLoginView.as_view(), name='login_user'),
    path('logout/', UserLogoutView.as_view(), name='logout_user'),
    path('register/', UserRegisterView.as_view(), name='register_user'),
    path('profile/', UserProfileView.as_view(), name='profile_user'),
    path('update/', UserUpdateView.as_view(), name='update_user'),
    path('change_password/', UserChangePasswordView.as_view(), name='change_password_user'),
    path('profile/genpassword/', user_generate_new_password, name='user_generate_new_password'),

    # Просмотр списка пользователей
    path('all_users/', UserListView.as_view(), name='users_list'),
    path('profile/<int:pk>/', UserProfileListView.as_view(), name='profile_user_view'),
]

dogs/models.py
from django.db import models
from django.conf import settings
from users.models import NULLABLE


class Category(models.Model):
    """
    Представляет категорию породы для собак.

    Атрибуты:
        name (str): Название породы.
        description (str): Описание породы.
    """

    name = models.CharField(max_length=100, verbose_name="breed")
    description = models.CharField(max_length=1000, verbose_name="description")

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'breed'
        verbose_name_plural = 'breeds'


class Dog(models.Model):
    """
    Представляет собаку в системе.

    Атрибуты:
        name (str): Имя собаки.
        category (Category): Порода собаки.
        photo (ImageField): Фото собаки.
        birth_date (date): Дата рождения собаки.
    """

    name = models.CharField(max_length=250, verbose_name="dog_name")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="breed")
    photo = models.ImageField(upload_to='dogs/', verbose_name="photo", **NULLABLE)
    birth_date = models.DateField(verbose_name="birth_date", **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,  on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name="Владелец")
    is_active = models.BooleanField(default=True, verbose_name="is_active")
    views = models.PositiveIntegerField(default=0, verbose_name="просмотры")

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'dog'
        verbose_name_plural = 'dogs'

    def views_count(self):
        self.views += 1
        self.save()

class Parent(models.Model):
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, verbose_name="dog_name")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="breed")
    birth_date = models.DateField(verbose_name="birth_date", **NULLABLE)

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'parent'
        verbose_name_plural = 'parents'

dogs/forms.py
from django import forms
from dogs.models import Dog, Parent
import datetime

from users.forms import StyleFormMixin


class DogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Dog
        exclude = ('owner', 'is_active', 'views')

    def clean_birth_date(self):
        if self.cleaned_data['birth_date']:
            cleaned_data = self.cleaned_data['birth_date']
            now_year = datetime.datetime.now().year
            if cleaned_data.year > now_year:
                raise forms.ValidationError('Дата рождения не может быть в будущем')
            if cleaned_data.year < now_year - 30:
                raise forms.ValidationError('Покойников не берем.')

            return cleaned_data
        else:
            return self.cleaned_data['birth_date']


class DogAdminForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Dog
        fields = '__all__'

    def clean_birth_date(self):
        if self.cleaned_data['birth_date']:
            cleaned_data = self.cleaned_data['birth_date']
            now_year = datetime.datetime.now().year
            if cleaned_data.year > now_year:
                raise forms.ValidationError('Дата рождения не может быть в будущем')
            if cleaned_data.year < now_year - 30:
                raise forms.ValidationError('Покойников не берем.')

            return cleaned_data
        else:
            return self.cleaned_data['birth_date']


class ParentForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Parent
        fields = '__all__'

dogs/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404
from dogs.models import Dog, Category, Parent
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from dogs.forms import DogForm, ParentForm, DogAdminForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from dogs.templates.dogs.services import send_email
from users.models import UserRoles


def index(request):
    """
    Отображает главную страницу с тремя первыми собаками.

    Аргументы:
        request (HttpRequest): Объект запроса.

    Возвращает:
        HttpResponse: Ответ с отрендеренным шаблоном главной страницы.
    """
    context = {
        'object_list': Dog.objects.all()[:3],
        'title': 'Питомник - Главная'
    }

    return render(request, 'dogs/index.html', context)


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'dogs/categories.html'
    extra_context = {'title': 'Питомник - Все наши породы'}



# class DogCategoryListView(LoginRequiredMixin, ListView):
#     model = Dog
#     template_name = 'dogs/dogs.html'
#     extra_context = {'title': 'Питомник - Все наши собаки'}


class DogsListView(LoginRequiredMixin, ListView):
    model = Dog
    template_name = 'dogs/dogs.html'
    extra_context = {'title': 'Питомник - Все наши собаки'}

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


class DogDeactivateListView(LoginRequiredMixin, ListView):
    model = Dog
    template_name = 'dogs/dogs.html'
    extra_context = {'title': 'Питомник - неактивные собаки'}

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.role in [UserRoles.MODERATOR, UserRoles.ADMIN]:
            queryset = queryset.filter(is_active=False)
            return queryset
        if self.request.user.role == UserRoles.USER:
            queryset = queryset.filter(is_active=False, owner=self.request.user)
            return queryset


class DogCreateView(LoginRequiredMixin, CreateView):
    model = Dog
    form_class = DogForm
    template_name = 'dogs/create_update.html'
    success_url = reverse_lazy('dogs:list_dogs')
    extra_context = {'title': 'Добавление питомца'}

    def form_valid(self, form):
        if self.request.user.role != UserRoles.USER:
            raise PermissionDenied()
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class DogDetailView(DetailView):
    model = Dog
    template_name = 'dogs/detail.html'
    extra_context = {'title': 'Питомник - Информация о собаке'}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        object = self.get_object()
        context_data['title'] = f'{object.name} ({object.category})'
        dog_object_increase = get_object_or_404(Dog, pk=object.pk)
        # if object.owner != self.request.user and self.request.user.role not in [UserRoles.ADMIN, UserRoles.MODERATOR]
        if object.owner != self.request.user:
            dog_object_increase.views_count()
        if object.owner:
            object_owner_email = object.owner.email
            if dog_object_increase.views % 100 == 0 and dog_object_increase.views != 0:
                print(object_owner_email)
                send_email(dog_object_increase.name, object_owner_email, dog_object_increase.views)
        return context_data


class DogUpdateView(LoginRequiredMixin, UpdateView):
    model = Dog
    form_class = DogForm
    template_name = 'dogs/create_update.html'
    extra_context = {'title': 'Редактирование питомца'}

    def get_success_url(self):
        return reverse('dogs:detail_dog', kwargs={'pk': self.object.pk})

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_staff:
            # if self.object.owner != self.request.user and self.request.user.role != UserRoles.ADMIN:
            raise PermissionDenied()
        return self.object

    def get_form_class(self):
        dog_forms = {
            'admin': DogAdminForm,
            'moderator': DogForm,
            'user': DogForm,
        }
        user_role = self.request.user.role
        dog_form_class = dog_forms[user_role]
        return dog_form_class

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ParentFormset = inlineformset_factory(Dog, Parent, form=ParentForm, extra=1)
        if self.request.method == 'POST':
            formset = ParentFormset(self.request.POST, instance=self.object)
        else:
            formset = ParentFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        contex_data = self.get_context_data()
        formset = contex_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class DogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Dog
    template_name = 'dogs/delete.html'
    success_url = reverse_lazy('dogs:list_dogs')
    extra_context = {'title': 'Удаление питомца'}
    permission_required = 'dogs.delete_dog'

    # dogs.add_dog -  PermissionRequiredMixin + CreateView
    # dogs.view_dog -  PermissionRequiredMixin + DetailView
    # dogs.change_dog -  PermissionRequiredMixin + UpdateView

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_staff:
            raise PermissionDenied
        return self.object


class DogsSearchListView(LoginRequiredMixin, ListView):
    model = Dog
    template_name = 'dogs/dogs.html'
    extra_context = {'title': 'Питомник - Поиск'}

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Dog.objects.filter(
            Q(name__icontains=query) & Q(is_active=True)
        )
        return object_list


class DogsCategorySearchListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'dogs/categories.html'
    extra_context = {'title': 'Питомник - Поиск по породам'}

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Category.objects.filter(
            Q(name__icontains=query)
        )
        return object_list


def dog_toggle_activity(request, pk):
    dog = get_object_or_404(Dog, pk=pk)
    if request.user.role in [UserRoles.MODERATOR, UserRoles.ADMIN]:
        if dog.is_active:
            dog.is_active = False
        else:
            dog.is_active = True
        dog.save()
        return HttpResponseRedirect(reverse('dogs:list_dogs'))
    else:
        raise PermissionDenied

dogs/templates/dogs/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Add some information about the album below, the author, or any other
                        background context. Make it a few sentences long so folks can pick up some informative tidbits.
                        Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        {% if user.is_superuser %}
                        <a class="p-2 btn btn-success" href="/admin/">Админка</a>
                        <li><a href="{% url 'users:users_list' %}" class="text-white">Список пользователей </a></li>
                        {% endif %}
                        <li><a href="{% url 'dogs:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'dogs:categories' %}" class="text-white">Породы</a></li>
                        <li><a href="{% url 'dogs:list_dogs' %}" class="text-white">Собаки</a></li>

                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'reviews:list_reviews' %}" class="text-white">Отзывы</a></li>
                        <li><a href="{% url 'users:profile_user' %}" class="text-white">Профиль</a></li>
                        <li>{% include 'dogs/includes/inc_search_fields.html'  %}</li>
                        <form method="post" action="{% url 'users:logout_user' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">Выход</button>
                        </form>
                        {% else %}

                        <li><a href="{% url 'users:login_user' %}" class="text-white">Вход</a></li>
                        <li><a href="{% url 'users:register_user' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Питомник</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

dogs/templates/dogs/categories.html
{% extends 'dogs/base.html' %}
{% block content %}
    <h1>{{ title }}</h1>
    <ul>
        {% for category in object_list %}
            <li>{{ category.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

dogs/templates/dogs/create_update.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование собаки
                {% else %}
                Добавление собаки
                {% endif %}
            </div>
            <div class="card-body">
                <img class="card-img-top"
                     src="{{ object.photo|my_media }}" width="300" height="400"
                     alt="Card image cap">
                <div class="card-text">
                    <h4>{{ object.name }}</h4>
                    <p>{{ object.description }}</p>
                </div>
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-outline-success"
                       value="{% if object %}Сохранить{% else %}Добавить{% endif %}">
                {% if object %}
                <a href="{% url 'dogs:toggle_activity_dog' object.pk %}"
                   class="btn btn-outline-warning float-right">
                    {% if object.is_active %}
                    Деактивировать
                    {% else %}
                    Активировать
                    {% endif %}
                </a>
                {% endif %}
            </div>
            <div class="card-footer">
                <a href="{% url 'dogs:list_dogs' %}" class="btn btn-outline-primary">Назад</a>
                {% if object and user.is_superuser %}
                <a href="{% url 'dogs:delete_dog' object.pk %}" class="btn btn-outline-danger float-right">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Родословная
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/delete.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<h1 xmlns="http://www.w3.org/1999/html">Delete Dog</h1>
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Вы уверены что хотите удалить собаку?
                {% endif %}
            </div>
            <div class="card-body">
                <img class="card-img-top" src="{{ object.photo|my_media }}" width="300" height="320"
                     alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">{{ object.name|title }}</p>
                </div>
                <div class="card-footer">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-danger">
                        {% if object %}
                        Удалить
                        {% endif %}
                    </button>
                    <a href="{% url 'dogs:update_dog' object.pk %}" class="btn btn-outline-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}pip install redis

dogs/templates/dogs/detail.html
{% extends 'dogs/base.html' %}
{% load my_tags %}

{% block content %}


<div class="col-md-4">

    <div class="card mb-4 box-shadow">
        <img class="card-img-top" src="{{ object.photo|my_media }}" width="300" height="320" alt="Card image cap">
        <div class="card-body">
            <p class="card-text">
                <td>Кличка</td>
                {{ object.name|title }}
            </p>
            <span class="text-muted"><td>Дата рождения: </td> {{ object.birth_date|default:"-" }}</span><br>
            <span class="text-muted"><td>Владелец: </td> {{ object.owner.first_name|default:"Без хозяина" }}</span><br>
            <span class="text-muted"><td>Телефон владельца: </td> {{ object.owner.phone|default:"не указан" }}</span><br>
            <span class="text-muted"><td>Просмотры: </td> {{ object.views }}</span><br>
        </div>
        <div class="card-footer">
            <a class="btn btn-link" href="{% url 'dogs:list_dogs' %}">назад</a>
            {% if user.is_staff or user == object.owner %}
            <a class="btn btn-link" href="{% url 'dogs:update_dog' object.pk %}">обновить</a>
            <a class="btn btn-link" href="{% url 'dogs:delete_dog' object.pk %}">удалить</a>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'dogs/includes/inc_dog_card.html' with object=object %}
        {% endfor %}
        </div>
    {% include 'dogs/includes/inc_pagination.html' with page_obj=page_obj %}
        <a href="{% url 'dogs:create_dog' %}" class="btn btn-outline-primary m-2 float-left">Добавить собаку</a>
        <a href="{% url 'dogs:deactivated_list_dogs' %}" class="btn btn-outline-secondary m-2 float-right">Неактивные собаки</a>
        <a href="{% url 'dogs:list_dogs' %}" class="btn btn-outline-success m-2 float-right">Активные собаки</a>
    </div>
{% endblock %}

dogs/templates/dogs/dogs_search_results.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

{% include 'dogs/includes/inc_search_fields.html'  %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'dogs/includes/inc_dog_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'dogs/includes/inc_pagination.html' with page_obj=page_obj %}
    <a href="{% url 'dogs:create_dog' %}" class="btn btn-outline-primary m-2 float-left">Добавить собаку</a>
    <a href="{% url 'dogs:deactivated_list_dogs' %}" class="btn btn-outline-secondary m-2 float-right">Неактивные
        собаки</a>
    <a href="{% url 'dogs:list_dogs' %}" class="btn btn-outline-success m-2 float-right">Активные собаки</a>
</div>
{% endblock %}

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}
{% load my_tags %}

{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{{ object.photo|my_media }}" width="300" height="320" alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
            </div>
            <div class="card-footer">
                <a class="btn btn-link" href="{% url 'dogs:detail_dog' object.pk %}">подробнее</a>
            </div>
        </div>

    </div>
    {% endfor %}
</div>

{% endblock %}

dogs/templates/dogs/update.html
{% extends 'dogs/base.html' %}
{% block content %}

    <h1>Update a Dog</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>

{% endblock %}