config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('dogs.urls', namespace='dogs')),
                  path('users/', include('users.urls', namespace='users')),
                  path('reviews/', include('reviews.urls', namespace='reviews')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from dogs.views import index, \
    DogsListView, DogCreateView, DogDetailView, DogUpdateView, DogDeleteView, CategoryListView, DogDeactivateListView, \
    dog_toggle_activity, DogsSearchListView, DogsCategorySearchListView
from dogs.apps import DogsConfig

app_name = DogsConfig.name

urlpatterns = [
    path('', cache_page(60)(index), name='index'),
    path('categories/', cache_page(60)(CategoryListView.as_view()), name='categories'),
    path('categories/<int:pk>/dogs', cache_page(60)(CategoryListView.as_view()), name='category_dogs'),
    path('dogs/', never_cache(DogsListView.as_view()), name='list_dogs'),
    path('dogs/deactivate/', DogDeactivateListView.as_view(), name='deactivated_list_dogs'),
    path('dogs/search/', DogsSearchListView.as_view(), name='search_dogs'),
    path('dogs/search/category/', DogsCategorySearchListView.as_view(), name='search_category_dogs'),
    path('dogs/create/', DogCreateView.as_view(), name='create_dog'),
    path('dogs/detail/<int:pk>/', never_cache(DogDetailView.as_view()), name='detail_dog'),
    path('dogs/update/<int:pk>/', never_cache(DogUpdateView.as_view()), name='update_dog'),
    path('dogs/toggle/<int:pk>/', dog_toggle_activity, name='toggle_activity_dog'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='delete_dog'),
]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import user_generate_new_password, UserRegisterView, \
    UserLoginView, UserProfileView, UserUpdateView, UserChangePasswordView, UserLogoutView, UserListView, UserProfileListView

app_name = UsersConfig.name

urlpatterns = [
    # работа с аккаунтом пользователя
    path('', UserLoginView.as_view(), name='login_user'),
    path('logout/', UserLogoutView.as_view(), name='logout_user'),
    path('register/', UserRegisterView.as_view(), name='register_user'),
    path('profile/', UserProfileView.as_view(), name='profile_user'),
    path('update/', UserUpdateView.as_view(), name='update_user'),
    path('change_password/', UserChangePasswordView.as_view(), name='change_password_user'),
    path('profile/genpassword/', user_generate_new_password, name='user_generate_new_password'),

    # Просмотр списка пользователей
    path('all_users/', UserListView.as_view(), name='users_list'),
    path('profile/<int:pk>/', UserProfileListView.as_view(), name='profile_user_view'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

NULLABLE = {'null': True, 'blank': True}

class UserRoles(models.TextChoices):
    """Class need for different level of permission, it depends of User.role
    (Класс необходимый для различных уровней доступа, доступ зависит от User,role)"""
    ADMIN = 'admin', _('admin')
    MODERATOR = 'moderator', _('moderator')
    USER = 'user', _('user')

class User(AbstractUser):
    username = None
    last_name = models.CharField(max_length=50, default='Anonymous')
    first_name = models.CharField(max_length=50, default='Anonymous')
    # pk = models.AutoField(primary_key=True)
    email = models.EmailField(unique=True)
    role = models.CharField(max_length=9, choices=UserRoles.choices, default=UserRoles.USER)
    phone = models.CharField(max_length=15, **NULLABLE)
    address = models.TextField(**NULLABLE)
    date_of_birth = models.DateField(**NULLABLE)
    telegram = models.CharField(max_length=50, verbose_name='Telegram Username', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Avatar', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='active')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['id']

users/forms.py
from django import forms

from users.models import User
from users.validators import validate_password
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'telegram', 'avatar',)


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        temp_data = self.cleaned_data
        validate_password(temp_data['password1'])
        if temp_data['password1'] != temp_data['password2']:
            raise forms.ValidationError('password_mismatch')
        return temp_data['password2']


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    pass


class UserUpdateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'telegram', 'avatar',)


class UserPasswordChangeForm(StyleFormMixin, PasswordChangeForm):
    def clean_new_password2(self):
        password1 = self.cleaned_data.get("new_password1")
        password2 = self.cleaned_data.get("new_password2")
        validate_password(password1)
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )

        password_validation.validate_password(password2, self.user)
        return password2

users/views.py
from django.shortcuts import reverse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView, LoginView, LogoutView
from django.shortcuts import reverse, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm, UserPasswordChangeForm
from users.models import User
from users.services import send_new_password_email, send_registration_email


class UserRegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register_user.html'
    success_url = reverse_lazy('users:login_user')

    def form_valid(self, form):
        self.object = form.save()
        send_registration_email(self.object.email)
        return super().form_valid(form)

class UserLoginView(LoginView):
    template_name = 'users/login_user.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('users:profile_user')

    def get_success_url(self):
        return reverse('users:profile_user')


class UserProfileView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/user_profile_read_only.html'

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/update_user.html'
    success_url = reverse_lazy('users:profile_user')

    def get_object(self, queryset=None):
        return self.request.user


class UserChangePasswordView(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'users/change_password_user.html'
    success_url = reverse_lazy('users:profile_user')


class UserLogoutView(LogoutView):
    pass
    template_name = 'users/logout_user.html'

class UserListView(ListView):
    model = User
    template_name = 'users/users.html'
    extra_context = {'title': 'Питомник - Список пользователей'}

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset

class UserProfileListView(DetailView):
    model = User
    template_name = 'users/user_view_profile.html'
    extra_context = {'title': 'Питомник - Профиль пользователя'}

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


@login_required
def user_generate_new_password(request):
    new_password = User.objects.make_random_password()
    request.user.set_password(new_password)
    request.user.save()
    send_new_password_email(request.user.email, new_password)
    return redirect(reverse('dogs:index'))

users/templates/users/change_password_user.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Изменение пароля</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login_user.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Авторизация пользователя</div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Вход</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/logout_user.html
{% extends 'dogs/base.html' %}

{% block content %}

<h1>Вы успешно вышли из аккаунта.</h1>
<p>Cпасибо за использование нашего сайта.</p>
<a href="{% url 'users:login_user' %}" class="btn btn-primary">Войти снова</a>
    {% endblock %}

users/templates/users/register_user.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Регистрация</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/update_user.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row">
<div class="col-3"></div>
<div class="col-6">
<div class="card">
    <div class="card-header">Редактирование пользователя
</div>
<div class="card-body">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Сохранить</button>
    </form>
</div>
</div>
</div>
</div>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Мой профиль
            </div>
            <img class="card-img-top"
                 src="{{ user.avatar|user_media }}" width="300" height="700"
                 alt="Card image cap">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-outline-warning">
                        <a class="btn btn-link" href="{% url 'users:update_user' %}">обновить</a>
                    </button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_profile_read_only.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Мой профиль
            </div>
            <img class="card-img-top"
                 src="{{ user.avatar|user_media }}" width="300" height="700"
                 alt="Card image cap">
            <div class="card-body">
                <span class="card-text">Почта: {{user.email}}</span><br>
                <span class="card-text">Имя: {{user.first_name}}</span><br>
                <span class="card-text">Фамилия: {{user.last_name}}</span><br>
                <span class="card-text">Телефон: {{user.phone|default:'Не указано'}}</span><br>
                <span class="card-text">Телеграм-аккаунт: {{user.telegram|default:'Не указано'}}</span><br>

                <button class="btn btn-outline-primary">
                    <a class="btn btn-link" href="{% url 'users:update_user' %}">Обновить</a>
                </button>

                <button class="btn btn-outline-primary">
                    <a class="btn btn-link" href="{% url 'users:change_password_user' %}">Изменить пароль</a>
                </button>

                <button class="btn btn-outline-danger">
                    <a class="btn btn-link" href="{% url 'users:user_generate_new_password' %}">Сгенерировать случайный
                        пароль</a>
                </button>

            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_view_profile.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Профиль {{ object.first_name }}
            </div>
            <img class="card-img-top"
                 src="{{ object.avatar|user_media }}" width="300" height="700"
                 alt="Card image cap">
            <div class="card-body">
                <span class="card-text">Почта: {{ object.email }}</span><br>
                <span class="card-text">Имя: {{ object.first_name|default:"Не указано" }}</span><br>
                <span class="card-text">Фамилия: {{ object.last_name|default:"Не указано" }}</span><br>
                <span class="card-text">Телефон: {{ object.phone|default:"Не указано" }}</span><br>
                <span class="card-text">Telegram: {{ object.telegram|default:"Не указано" }}</span><br>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:users_list' %}" class="btn btn-primary">Назад</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/users.html
{% extends 'dogs/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'users/includes/inc_user_card.html' with object=object %}
        {% endfor %}
        </div>
    </div>
{% endblock %}